---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull meetgoswami/scientific_calculator:calc_1
      
    - name: running container
      shell: docker run -it -d meetgoswami/scientific_calculator:calc_1
